In [63]:
import pandas as pd 
import seaborn as sns 
from pathlib import Path

In [64]:
BASE_DIR = Path('merged_ESS5_reordered.csv').resolve().parent 
data_path = BASE_DIR / 'combined_data' / 'merged_ESS5_reordered.csv'
df = pd.read_csv(data_path) # called file in portable way

In [65]:
cols_to_remove = ['dweight', 'pspwght', 'pweight', 'anweight']
filtered_df = df.drop(columns=cols_to_remove)
filtered_df
filtered_df.columns

Index(['name', 'essround', 'edition', 'proddate', 'idno', 'cntry', 'prtmbcbe',
       'prtvtcbe', 'prtmbbbg', 'prtvtbbg', 'prtmbcch', 'prtvtcch', 'prtmbcy',
       'prtvtcy', 'prtmbbcz', 'prtvtbcz', 'prtmbcde', 'prtvcde1', 'prtvcde2',
       'prtmbbdk', 'prtvtbdk', 'prtmbcee', 'prtvtcee', 'prtmbbes', 'prtvtbes',
       'prtmbbfi', 'prtvtbfi', 'prtmbcfr', 'prtvtbfr', 'prtmbgb', 'prtvtgb',
       'prtmbcgr', 'prtvtcgr', 'prtmbhr', 'prtvthr', 'prtmbchu', 'prtvtchu',
       'prtmbbie', 'prtvtaie', 'prtmbbil', 'prtvtbil', 'prtmblt', 'prtvlt1',
       'prtvlt2', 'prtvlt3', 'prtmbcnl', 'prtvtdnl', 'prtmbano', 'prtvtano',
       'prtmbdpl', 'prtvtbpl', 'prtmbbpt', 'prtvtbpt', 'prtmbbru', 'prtvtbru',
       'prtmbase', 'prtvtase', 'prtmbcsi', 'prtvtcsi', 'prtmbbsk', 'prtvtbsk',
       'prtmbcua', 'prtvtbua'],
      dtype='object')

In [66]:
prtvt_df = filtered_df.melt(
    id_vars = ['idno', 'cntry'],
    value_vars = [
        'prtvtcbe', 'prtvtbbg', 'prtvtcch', 'prtvtcy', 'prtvtbcz', 
        'prtvcde1', 'prtvcde2', 'prtvtbdk', 'prtvtcee', 'prtvtbes', 
        'prtvtbfi', 'prtvtbfr', 'prtvtgb', 'prtvtcgr', 'prtvthr', 
        'prtvtchu', 'prtvtaie', 'prtvtbil', 'prtvlt1', 'prtvlt2', 
        'prtvlt3', 'prtvtdnl', 'prtvtano', 'prtvtbpl', 'prtvtbpt', 
        'prtvtbru', 'prtvtase', 'prtvtcsi', 'prtvtbsk', 'prtvtbua'
    ],
    var_name = 'Party Vote Code', # This tells you WHICH country column it came from
    value_name = 'Last Party Voted For'   # This is the ACTUAL value (e.g., 1.0, 5.0)
)

new_party_vote_values = {
    'prtvtcbe': 'Party Vote in Last Election in Belgium',
    'prtvtbbg': 'Party Vote in Last Election in Bulgaria',
    'prtvtcch': 'Party Vote in Last Election in Switzerland',
    'prtvtcy': 'Party Vote in Last Election in Cyprus', 
    'prtvtbcz': 'Party Vote in Last Election in Czechia',
    'prtvcde1': 'Party Vote in Last Election in Germany (Candidate)',
    'prtvcde2': 'Party Vote in Last Election in Germany (List)',
    'prtvtbdk': 'Party Vote in Last Election in Denmark',
    'prtvtcee': 'Party Vote in Last Election in Estonia',
    'prtvtbes': 'Party Vote in Last Election in Spain',
    'prtvtbfi': 'Party Vote in Last Election in Finland',
    'prtvtbfr': 'Party Vote in Last Election in France',
    'prtvtgb': 'Party Vote in Last Election in Great Britain', 
    'prtvtcgr': 'Party Vote in Last Election in Greece',
    'prtvthr': 'Party Vote in Last Election in Croatia',
    'prtvtchu': 'Party Vote in Last Election in Hungary',
    'prtvtaie': 'Party Vote in Last Election in Ireland',
    'prtvtbil': 'Party Vote in Last Election in Israel',
    'prtvlt1': 'Party Vote in Last Election in Lithuania (1)',
    'prtvlt2': 'Party Vote in Last Election in Lithuania (2)',
    'prtvlt3': 'Party Vote in Last Election in Lithuania (3)',
    'prtvtdnl': 'Party Vote in Last Election in Netherlands',
    'prtvtano': 'Party Vote in Last Election in Norway',
    'prtvtbpl': 'Party Vote in Last Election in Poland',
    'prtvtbpt': 'Party Vote in Last Election in Portugal',
    'prtvtbru': 'Party Vote in Last Election in the Russian Federation',
    'prtvtase': 'Party Vote in Last Election in Sweden',
    'prtvtcsi': 'Party Vote in Last Election in Slovenia',
    'prtvtbsk': 'Party Vote in Last Election in Slovakia', 
    'prtvtbua': 'Party Vote in Last Election in Ukraine'}

prtvt_df['Party Vote Code'] = prtvt_df['Party Vote Code'].replace(new_party_vote_values)
prtvt_df.head(20)

      idno cntry                         Party Vote Code  Last Party Voted For
0   100102    BE  Party Vote in Last Election in Belgium                   1.0
1   100106    BE  Party Vote in Last Election in Belgium                  66.0
2   100202    BE  Party Vote in Last Election in Belgium                  88.0
3   100204    BE  Party Vote in Last Election in Belgium                   8.0
4   100209    BE  Party Vote in Last Election in Belgium                   5.0
5   100301    BE  Party Vote in Last Election in Belgium                   3.0
6   100307    BE  Party Vote in Last Election in Belgium                   8.0
7   100308    BE  Party Vote in Last Election in Belgium                   8.0
8   100309    BE  Party Vote in Last Election in Belgium                   8.0
9   100401    BE  Party Vote in Last Election in Belgium                   5.0
10  100402    BE  Party Vote in Last Election in Belgium                  17.0
11  100403    BE  Party Vote in Last Election in Belgium                   8.0
12  100405    BE  Party Vote in Last Election in Belgium                   3.0
13  100406    BE  Party Vote in Last Election in Belgium                   3.0
14  100408    BE  Party Vote in Last Election in Belgium                  66.0
15  100502    BE  Party Vote in Last Election in Belgium                   5.0
16  100503    BE  Party Vote in Last Election in Belgium                   3.0
17  100504    BE  Party Vote in Last Election in Belgium                  17.0
18  100505    BE  Party Vote in Last Election in Belgium                   8.0
19  100507    BE  Party Vote in Last Election in Belgium                   2.0

In [ ]:
prtmb_df = df.melt(
    id_vars = ['idno', 'cntry'],
    value_vars = ['prtmbcbe', 'prtmbbbg', 'prtmbcch', 'prtmbcy', 'prtmbbcz', 'prtmbcde',
       'prtmbbdk', 'prtmbcee', 'prtmbbes', 'prtmbbfi', 'prtmbcfr', 'prtmbgb','prtmbcgr', 
       'prtmbhr', 'prtmbchu', 'prtmbbie', 'prtmbbil', 'prtmblt', 'prtmbcnl', 
       'prtmbano', 'prtmbdpl', 'prtmbbpt', 'prtmbbru', 'prtmbase', 'prtmbcsi', 'prtmbbsk',
       'prtmbcua'],
    var_name = 'Party Membership by Country', # This tells you WHICH country column it came from
    value_name = 'Party Membership by Voter')   # This is the ACTUAL value (e.g., 1.0, 5.0)
prtmb_df

party_membership_dict = {'prtmbcbe': 'Party Membership in Belgium', 
                         'prtmbbbg': 'Party Membership in Bulgaria',
                         'prtmbcch': 'Party Membership in Switzerland', 
                         'prtmbcy': 'Party Membership in Cyrus', 
                         'prtmbbcz': 'Party Membership in Czechia', 
                         'prtmbcde': 'Party Membership in Germany',
                         'prtmbbdk': 'Party Membership in Denmark',
                         'prtmbcee': 'Party Membership in Estonia', 'prtmbbes', 'prtmbbfi', 'prtmbcfr', 'prtmbgb','prtmbcgr', 
       'prtmbhr', 'prtmbchu', 'prtmbbie', 'prtmbbil', 'prtmblt', 'prtmbcnl', 
       'prtmbano', 'prtmbdpl', 'prtmbbpt', 'prtmbbru', 'prtmbase', 'prtmbcsi', 'prtmbbsk',
       'prtmbcua'}

           idno cntry Party Membership by Country  Party Membership by Voter
0        100102    BE                    prtmbcbe                       66.0
1        100106    BE                    prtmbcbe                       66.0
2        100202    BE                    prtmbcbe                       66.0
3        100204    BE                    prtmbcbe                       66.0
4        100209    BE                    prtmbcbe                       66.0
...         ...   ...                         ...                        ...
1416361    2996    UA                    prtmbcua                       66.0
1416362    2997    UA                    prtmbcua                       66.0
1416363    2998    UA                    prtmbcua                       66.0
1416364    3001    UA                    prtmbcua                       66.0
1416365    3002    UA                    prtmbcua                       66.0

[1416366 rows x 4 columns]

In [95]:
concat_df = pd.concat([prtvt_df, prtmb_df], axis=1)
final_df = concat_df.loc[:, ~concat_df.columns.duplicated()]
final_df

,idno,cntry,Party Vote Code,Last Party Voted For,Party Membership by Country,Party Membership by Voter
0,100102,BE,Party Vote in Last Election in Belgium,1.0,prtmbcbe,66.0
1,100106,BE,Party Vote in Last Election in Belgium,66.0,prtmbcbe,66.0
2,100202,BE,Party Vote in Last Election in Belgium,88.0,prtmbcbe,66.0
3,100204,BE,Party Vote in Last Election in Belgium,8.0,prtmbcbe,66.0
4,100209,BE,Party Vote in Last Election in Belgium,5.0,prtmbcbe,66.0
...,...,...,...,...,...,...
1573735,2996,UA,Party Vote in Last Election in Ukraine,77.0,NaN,NaN
1573736,2997,UA,Party Vote in Last Election in Ukraine,77.0,NaN,NaN
1573737,2998,UA,Party Vote in Last Election in Ukraine,2.0,NaN,NaN
1573738,3001,UA,Party Vote in Last Election in Ukraine,2.0,NaN,NaN
1573739,3002,UA,Party Vote in Last Election in Ukraine,2.0,NaN,NaN